/*
 * Stack da Trilha React: 93 tecnologias, ferramentas e metodologias em 13
 * categorias, com os aprendizados onde aparecem e o status de cada uma.
 */
import type { Categoria, Tecnologia } from '../dominio/tipos'

export const categorias: Categoria[] = [
  {
    numero: 1,
    nome: 'Linguagens e base',
  },
  {
    numero: 2,
    nome: 'Ambiente, build e produtividade',
  },
  {
    numero: 3,
    nome: 'Fundamentos e APIs do React',
  },
  {
    numero: 4,
    nome: 'Estilização e UI',
  },
  {
    numero: 5,
    nome: 'Rotas e navegação',
  },
  {
    numero: 6,
    nome: 'Dados e comunicação com API',
  },
  {
    numero: 7,
    nome: 'Gerenciamento de estado',
  },
  {
    numero: 8,
    nome: 'Formulários e validação',
  },
  {
    numero: 9,
    nome: 'Back-end, banco e infraestrutura',
  },
  {
    numero: 10,
    nome: 'Autenticação e segurança',
  },
  {
    numero: 11,
    nome: 'Frameworks fullstack',
  },
  {
    numero: 12,
    nome: 'IA aplicada ao desenvolvimento',
  },
  {
    numero: 13,
    nome: 'Metodologias, padrões e práticas',
  },
]

export const tecnologias: Tecnologia[] = [
  {
    numero: 1,
    categoria: 1,
    nome: 'JavaScript (ES6+)',
    oQueE: 'Linguagem da web, com arrow functions, desestruturação, módulos, async/await',
    paraQue: 'Base de tudo no React; sem ES6 o código React não é legível',
    aprendizados: [1, 11],
    status: 'atual',
  },
  {
    numero: 2,
    categoria: 1,
    nome: 'React',
    oQueE: 'Biblioteca de interfaces baseada em componentes',
    paraQue: 'Construir telas que se atualizam sozinhas quando os dados mudam',
    aprendizados: [1],
    status: 'atual',
  },
  {
    numero: 3,
    categoria: 1,
    nome: 'JSX',
    oQueE: 'Sintaxe que mistura HTML e JavaScript',
    paraQue: 'Descrever a interface dentro do componente',
    aprendizados: [1],
    status: 'atual',
  },
  {
    numero: 4,
    categoria: 1,
    nome: 'TypeScript',
    oQueE: 'JavaScript com tipos',
    paraQue: 'Pegar erros antes de rodar e documentar props, estados e respostas de API',
    aprendizados: [9, 36, 45],
    status: 'atual',
  },
  {
    numero: 5,
    categoria: 1,
    nome: 'Rust',
    oQueE: 'Linguagem compilada focada em performance e segurança de memória',
    paraQue: 'Núcleo nativo de apps desktop com Tauri',
    aprendizados: [110],
    status: 'atual',
    nota: 'nicho',
  },
  {
    numero: 6,
    categoria: 2,
    nome: 'Vite',
    oQueE: 'Ferramenta de criação e build de projetos, muito rápida',
    paraQue: 'Iniciar e empacotar projetos React hoje',
    aprendizados: [1],
    status: 'atual',
  },
  {
    numero: 7,
    categoria: 2,
    nome: 'Snowpack',
    oQueE: 'Build tool sem empacotamento, citada como comparação',
    paraQue: 'Só como contexto histórico do Vite',
    aprendizados: [1],
    status: 'historico',
  },
  {
    numero: 8,
    categoria: 2,
    nome: 'npm / Yarn',
    oQueE: 'Gerenciadores de pacotes',
    paraQue: 'Instalar bibliotecas e rodar scripts',
    aprendizados: [1],
    status: 'atual',
  },
  {
    numero: 9,
    categoria: 2,
    nome: 'VS Code',
    oQueE: 'Editor de código',
    paraQue: 'Desenvolvimento, com extensões, snippets e formatação',
    aprendizados: [4],
    status: 'atual',
  },
  {
    numero: 10,
    categoria: 2,
    nome: 'create-react-app (CRA)',
    oQueE: 'Gerador oficial antigo de projetos React',
    paraQue: 'Entender projetos legados; não usar em projeto novo',
    aprendizados: [22],
    status: 'historico',
  },
  {
    numero: 11,
    categoria: 2,
    nome: 'Caminhos absolutos (alias)',
    oQueE: 'Configuração de imports curtos',
    paraQue: 'Trocar "../../../" por "@/components"',
    aprendizados: [18],
    status: 'atual',
  },
  {
    numero: 12,
    categoria: 2,
    nome: 'ESLint',
    oQueE: 'Analisador de código',
    paraQue: 'Padronizar o estilo e apontar erros comuns',
    aprendizados: [80],
    status: 'atual',
  },
  {
    numero: 13,
    categoria: 2,
    nome: 'Bun',
    oQueE: 'Runtime JavaScript rápido, alternativa ao Node',
    paraQue: 'Back-end e scripts com menos configuração',
    aprendizados: [59],
    status: 'atual',
  },
  {
    numero: 14,
    categoria: 3,
    nome: 'Componentes e props',
    oQueE: 'Peças reutilizáveis que recebem dados do pai',
    paraQue: 'Dividir a tela em partes e reaproveitar código',
    aprendizados: [5],
    status: 'atual',
  },
  {
    numero: 15,
    categoria: 3,
    nome: 'useState',
    oQueE: 'Hook de estado local',
    paraQue: 'Guardar valores que mudam a interface (input, contador, lista)',
    aprendizados: [6],
    status: 'atual',
  },
  {
    numero: 16,
    categoria: 3,
    nome: 'useEffect',
    oQueE: 'Hook de efeitos colaterais',
    paraQue: 'Buscar API, assinar eventos, sincronizar com algo externo',
    aprendizados: [7],
    status: 'atual',
  },
  {
    numero: 17,
    categoria: 3,
    nome: 'useMemo',
    oQueE: 'Memoriza um valor calculado',
    paraQue: 'Evitar recálculos caros a cada renderização',
    aprendizados: [10],
    status: 'atual',
  },
  {
    numero: 18,
    categoria: 3,
    nome: 'useCallback',
    oQueE: 'Memoriza uma função',
    paraQue: 'Manter a mesma referência de função entre renderizações',
    aprendizados: [11, 55],
    status: 'atual',
  },
  {
    numero: 19,
    categoria: 3,
    nome: 'Custom hooks',
    oQueE: 'Hooks criados por você',
    paraQue: 'Extrair e reaproveitar lógica (ex.: useFetch)',
    aprendizados: [11],
    status: 'atual',
  },
  {
    numero: 20,
    categoria: 3,
    nome: 'Componentes de classe',
    oQueE: 'Forma antiga de escrever componentes',
    paraQue: 'Ler código legado',
    aprendizados: [12, 116],
    status: 'historico',
  },
  {
    numero: 21,
    categoria: 3,
    nome: 'Regras dos hooks',
    oQueE: 'Hooks só no topo do componente, nunca em condicionais',
    paraQue: 'Evitar bugs de estado trocado',
    aprendizados: [13],
    status: 'atual',
  },
  {
    numero: 22,
    categoria: 3,
    nome: 'useRef',
    oQueE: 'Referência que persiste sem renderizar de novo',
    paraQue: 'Acessar o DOM (foco, scroll) e guardar valores mutáveis',
    aprendizados: [15],
    status: 'atual',
  },
  {
    numero: 23,
    categoria: 3,
    nome: 'forwardRef / useImperativeHandle',
    oQueE: 'Expõe a ref ou funções do filho para o pai',
    paraQue: 'Componentes de biblioteca (input customizado, modal)',
    aprendizados: [16],
    status: 'transicao',
    nota: 'simplificado no React 19',
  },
  {
    numero: 24,
    categoria: 3,
    nome: 'Context API',
    oQueE: 'Estado compartilhado sem passar props em cascata',
    paraQue: 'Tema, usuário logado, idioma',
    aprendizados: [20, 46],
    status: 'atual',
  },
  {
    numero: 25,
    categoria: 3,
    nome: 'React.memo',
    oQueE: 'Evita renderizar de novo quando as props não mudam',
    paraQue: 'Otimizar listas e componentes pesados',
    aprendizados: [55],
    status: 'atual',
  },
  {
    numero: 26,
    categoria: 3,
    nome: 'React 18: concorrência',
    oQueE: 'Renderização concorrente, transições, batching automático',
    paraQue: 'Interfaces que continuam fluidas em atualizações pesadas',
    aprendizados: [97],
    status: 'atual',
  },
  {
    numero: 27,
    categoria: 3,
    nome: 'React 19: use, Actions, ref como prop',
    oQueE: 'Novas APIs que reduzem o useEffect e simplificam formulários',
    paraQue: 'Projetos novos com código mais simples',
    aprendizados: [98, 99, 100],
    status: 'atual',
  },
  {
    numero: 28,
    categoria: 3,
    nome: 'React 19.2: Activity, useEffectEvent',
    oQueE: 'Novidades recentes da versão 19.2',
    paraQue: 'Manter telas escondidas vivas; efeitos sem dependências indevidas',
    aprendizados: [101],
    status: 'atual',
  },
  {
    numero: 29,
    categoria: 4,
    nome: 'CSS e componentes estilizados',
    oQueE: 'Estilo aplicado e reutilizado por componente',
    paraQue: 'Consistência visual',
    aprendizados: [8],
    status: 'atual',
  },
  {
    numero: 30,
    categoria: 4,
    nome: 'Styled Components',
    oQueE: 'CSS-in-JS: estilos escritos em JavaScript',
    paraQue: 'Estilo com props e temas dentro do componente',
    aprendizados: [19],
    status: 'transicao',
  },
  {
    numero: 31,
    categoria: 4,
    nome: 'Stitches',
    oQueE: 'CSS-in-JS com foco em performance (citado)',
    paraQue: 'Contexto; o projeto foi descontinuado',
    aprendizados: [1],
    status: 'historico',
  },
  {
    numero: 32,
    categoria: 4,
    nome: 'Bootstrap / React Bootstrap',
    oQueE: 'Framework de componentes prontos',
    paraQue: 'Protótipos e painéis administrativos rápidos (tabs, tabela, modal)',
    aprendizados: [25],
    status: 'transicao',
  },
  {
    numero: 33,
    categoria: 4,
    nome: 'Tailwind CSS (v3 → v4)',
    oQueE: 'CSS utilitário direto no HTML',
    paraQue: 'Estilizar rápido, com design consistente',
    aprendizados: [61, 62, 63],
    status: 'atual',
  },
  {
    numero: 34,
    categoria: 4,
    nome: 'Radix UI',
    oQueE: 'Componentes sem estilo, acessíveis',
    paraQue: 'Base de menus, diálogos e selects acessíveis',
    aprendizados: [54],
    status: 'atual',
  },
  {
    numero: 35,
    categoria: 4,
    nome: 'shadcn/ui',
    oQueE: 'Componentes (Radix + Tailwind) copiados para o projeto',
    paraQue: 'Montar interfaces profissionais rapidamente, sem dependência travada',
    aprendizados: [64],
    status: 'atual',
  },
  {
    numero: 36,
    categoria: 4,
    nome: 'Recharts',
    oQueE: 'Biblioteca de gráficos para React',
    paraQue: 'Dashboards e relatórios',
    aprendizados: [65],
    status: 'atual',
  },
  {
    numero: 37,
    categoria: 4,
    nome: 'Figma',
    oQueE: 'Ferramenta de design de interface',
    paraQue: 'Protótipo que vira código (inclusive com IA)',
    aprendizados: [67, 72],
    status: 'atual',
  },
  {
    numero: 38,
    categoria: 4,
    nome: 'Framer Motion',
    oQueE: 'Animações declarativas',
    paraQue: 'Transições e microinterações',
    aprendizados: [79],
    status: 'atual',
    nota: 'hoje "Motion"',
  },
  {
    numero: 39,
    categoria: 4,
    nome: 'Design responsivo',
    oQueE: 'Layout que se adapta a cada tela (media queries)',
    paraQue: 'Funcionar em celular, tablet e desktop',
    aprendizados: [71],
    status: 'atual',
  },
  {
    numero: 40,
    categoria: 4,
    nome: 'Tema escuro (dark theme)',
    oQueE: 'Variação de cores por tema',
    paraQue: 'Conforto visual e preferência do usuário',
    aprendizados: [20, 73],
    status: 'atual',
  },
  {
    numero: 41,
    categoria: 4,
    nome: 'Shimmer / skeleton',
    oQueE: 'Esqueleto animado durante o carregamento',
    paraQue: 'Reduzir a sensação de espera',
    aprendizados: [75],
    status: 'atual',
  },
  {
    numero: 42,
    categoria: 4,
    nome: 'Design System',
    oQueE: 'Conjunto padronizado de tokens e componentes',
    paraQue: 'Escalar a interface com consistência entre times',
    aprendizados: [113],
    status: 'atual',
  },
  {
    numero: 43,
    categoria: 5,
    nome: 'React Router',
    oQueE: 'Roteador padrão do React',
    paraQue: 'Páginas, parâmetros na URL, 404, rotas privadas',
    aprendizados: [1, 24],
    status: 'atual',
  },
  {
    numero: 44,
    categoria: 5,
    nome: 'Rotas privadas',
    oQueE: 'Bloqueio de páginas para quem não está logado',
    paraQue: 'Áreas restritas (painel, perfil)',
    aprendizados: [41],
    status: 'atual',
  },
  {
    numero: 45,
    categoria: 5,
    nome: 'TanStack Router',
    oQueE: 'Roteador com tipagem completa',
    paraQue: 'Apps TypeScript que querem rotas e parâmetros tipados',
    aprendizados: [50],
    status: 'atual',
  },
  {
    numero: 46,
    categoria: 6,
    nome: 'API REST + verbos HTTP',
    oQueE: 'GET, POST, PUT/PATCH, DELETE',
    paraQue: 'Ler e alterar dados no servidor (o CRUD)',
    aprendizados: [28, 29, 30, 31],
    status: 'atual',
  },
  {
    numero: 47,
    categoria: 6,
    nome: 'Fetch API',
    oQueE: 'Função nativa do navegador para requisições',
    paraQue: 'Chamar APIs sem biblioteca',
    aprendizados: [28],
    status: 'atual',
  },
  {
    numero: 48,
    categoria: 6,
    nome: 'JSON Server',
    oQueE: 'API REST falsa a partir de um arquivo JSON',
    paraQue: 'Praticar e prototipar o front sem back-end',
    aprendizados: [33],
    status: 'atual',
    nota: 'para estudo',
  },
  {
    numero: 49,
    categoria: 6,
    nome: 'SWR',
    oQueE: 'Busca de dados com cache e revalidação',
    paraQue: 'Dados do servidor sempre atualizados',
    aprendizados: [39],
    status: 'transicao',
  },
  {
    numero: 50,
    categoria: 6,
    nome: 'GraphQL + Apollo Client',
    oQueE: 'Linguagem de consulta e cliente para ela',
    paraQue: 'APIs em que o front escolhe os campos que quer',
    aprendizados: [40],
    status: 'transicao',
    nota: 'nicho',
  },
  {
    numero: 51,
    categoria: 6,
    nome: 'TanStack Query (React Query)',
    oQueE: 'Gerenciador de estado do servidor (cache, paginação, mutação)',
    paraQue: 'Substituir useEffect + useState no consumo de API',
    aprendizados: [47, 48],
    status: 'atual',
  },
  {
    numero: 52,
    categoria: 6,
    nome: 'Atualização otimista',
    oQueE: 'Mostrar o resultado antes da resposta do servidor',
    paraQue: 'Likes, favoritos e toggles instantâneos',
    aprendizados: [57],
    status: 'atual',
  },
  {
    numero: 53,
    categoria: 6,
    nome: 'tRPC / Eden / ZSA / Orval',
    oQueE: 'Contratos tipados entre front e back',
    paraQue: 'Mudança no back quebrar o build do front, e não a produção',
    aprendizados: [60],
    status: 'atual',
  },
  {
    numero: 54,
    categoria: 7,
    nome: 'Estado derivado',
    oQueE: 'Calcular a partir do estado existente, em vez de duplicar',
    paraQue: 'Evitar o erro mais comum do React',
    aprendizados: [14],
    status: 'atual',
    nota: 'conceito',
  },
  {
    numero: 55,
    categoria: 7,
    nome: 'Redux',
    oQueE: 'Store global com actions e reducers',
    paraQue: 'Estado global complexo e previsível',
    aprendizados: [42],
    status: 'transicao',
    nota: 'hoje Redux Toolkit',
  },
  {
    numero: 56,
    categoria: 7,
    nome: 'Redux Thunk',
    oQueE: 'Middleware para ações assíncronas',
    paraQue: 'Chamar a API a partir de actions',
    aprendizados: [44],
    status: 'historico',
  },
  {
    numero: 57,
    categoria: 7,
    nome: 'Redux Saga',
    oQueE: 'Middleware com generators para efeitos',
    paraQue: 'Fluxos assíncronos complexos (legado)',
    aprendizados: [45],
    status: 'historico',
  },
  {
    numero: 58,
    categoria: 7,
    nome: 'URL State',
    oQueE: 'Estado guardado na URL (query params)',
    paraQue: 'Filtros, busca e paginação compartilháveis',
    aprendizados: [49],
    status: 'atual',
  },
  {
    numero: 59,
    categoria: 7,
    nome: 'Local-first (ElectricSQL, TanStack DB)',
    oQueE: 'Dados locais que sincronizam com o servidor',
    paraQue: 'Apps offline e com resposta instantânea',
    aprendizados: [109],
    status: 'atual',
    nota: 'fronteira',
  },
  {
    numero: 60,
    categoria: 8,
    nome: 'React Hook Form',
    oQueE: 'Formulários performáticos com hooks',
    paraQue: 'Cadastros e checkouts sem renderização a cada tecla',
    aprendizados: [51, 52],
    status: 'atual',
  },
  {
    numero: 61,
    categoria: 8,
    nome: 'Zod',
    oQueE: 'Validação de dados por schema, com tipos',
    paraQue: 'A mesma regra no front e no back; tipos gerados automaticamente',
    aprendizados: [51, 91],
    status: 'atual',
  },
  {
    numero: 62,
    categoria: 9,
    nome: 'Node.js',
    oQueE: 'JavaScript no servidor',
    paraQue: 'API REST do projeto fullstack',
    aprendizados: [35],
    status: 'atual',
  },
  {
    numero: 63,
    categoria: 9,
    nome: 'MySQL',
    oQueE: 'Banco de dados relacional',
    paraQue: 'Persistir usuários e registros com integridade',
    aprendizados: [35],
    status: 'atual',
  },
  {
    numero: 64,
    categoria: 9,
    nome: 'Upload de arquivos',
    oQueE: 'Envio de arquivos com progresso',
    paraQue: 'Avatares, documentos, mídia',
    aprendizados: [37],
    status: 'atual',
    nota: 'funcionalidade',
  },
  {
    numero: 65,
    categoria: 9,
    nome: 'Heroku',
    oQueE: 'Plataforma de deploy',
    paraQue: 'Contexto; sem plano gratuito hoje',
    aprendizados: [38],
    status: 'historico',
  },
  {
    numero: 66,
    categoria: 9,
    nome: 'Serverless / Vercel',
    oQueE: 'Funções sob demanda sem servidor dedicado',
    paraQue: 'Back-end leve e deploy de apps Next',
    aprendizados: [82],
    status: 'atual',
  },
  {
    numero: 67,
    categoria: 9,
    nome: 'AWS',
    oQueE: 'Nuvem da Amazon',
    paraQue: 'Deploy próprio com mais controle e custo menor em escala',
    aprendizados: [96],
    status: 'atual',
  },
  {
    numero: 68,
    categoria: 10,
    nome: 'RBAC (controle por papéis)',
    oQueE: 'Permissões por perfil (admin, editor…)',
    paraQue: 'Definir quem pode fazer o quê',
    aprendizados: [58],
    status: 'atual',
  },
  {
    numero: 69,
    categoria: 10,
    nome: 'Better Auth',
    oQueE: 'Biblioteca moderna de autenticação',
    paraQue: 'Login, sessão e provedores sem reinventar',
    aprendizados: [59],
    status: 'atual',
  },
  {
    numero: 70,
    categoria: 10,
    nome: 'JWT',
    oQueE: 'Token assinado que identifica o usuário',
    paraQue: 'Autenticação entre front e API',
    aprendizados: [95],
    status: 'atual',
  },
  {
    numero: 71,
    categoria: 11,
    nome: 'Next.js',
    oQueE: 'Framework React fullstack',
    paraQue: 'SEO, SSR, rotas por arquivo e API no mesmo projeto',
    aprendizados: [80],
    status: 'atual',
  },
  {
    numero: 72,
    categoria: 11,
    nome: 'SSR / SSG',
    oQueE: 'Renderizar no servidor ou gerar páginas estáticas',
    paraQue: 'Carregamento rápido e SEO',
    aprendizados: [81],
    status: 'atual',
  },
  {
    numero: 73,
    categoria: 11,
    nome: 'App Router',
    oQueE: 'Roteamento por pastas com layouts (Next 13+)',
    paraQue: 'Estruturar apps Next modernos',
    aprendizados: [83, 89],
    status: 'atual',
  },
  {
    numero: 74,
    categoria: 11,
    nome: 'Server Components',
    oQueE: 'Componentes que rodam só no servidor',
    paraQue: 'Menos JavaScript no cliente; acesso direto a dados',
    aprendizados: [85, 86, 87],
    status: 'atual',
  },
  {
    numero: 75,
    categoria: 11,
    nome: 'Server Actions',
    oQueE: 'Funções no servidor chamadas pelo formulário',
    paraQue: 'Mutação sem criar endpoint manual',
    aprendizados: [88, 91],
    status: 'atual',
  },
  {
    numero: 76,
    categoria: 11,
    nome: 'Cache e revalidação (tags)',
    oQueE: 'Controle de dados em cache no Next',
    paraQue: 'Performance com dados sempre corretos',
    aprendizados: [94, 95],
    status: 'atual',
  },
  {
    numero: 77,
    categoria: 11,
    nome: 'Remix / React Router v7',
    oQueE: 'Framework fullstack, hoje incorporado ao React Router',
    paraQue: 'Alternativa ao Next focada em padrões web',
    aprendizados: [107, 108],
    status: 'atual',
  },
  {
    numero: 78,
    categoria: 11,
    nome: 'Tauri',
    oQueE: 'Framework de apps desktop (Rust + web)',
    paraQue: 'App desktop leve com interface em React',
    aprendizados: [110],
    status: 'atual',
    nota: 'nicho',
  },
  {
    numero: 79,
    categoria: 12,
    nome: 'IA Figma → código',
    oQueE: 'Geração de componentes a partir do design',
    paraQue: 'Acelerar a passagem design → front',
    aprendizados: [67],
    status: 'atual',
  },
  {
    numero: 80,
    categoria: 12,
    nome: 'OpenAI API',
    oQueE: 'Modelos de linguagem via API',
    paraQue: 'Funcionalidades inteligentes (resumo, classificação, chat)',
    aprendizados: [104],
    status: 'atual',
  },
  {
    numero: 81,
    categoria: 12,
    nome: 'Vercel AI SDK',
    oQueE: 'SDK para integrar IA com streaming no React/Next',
    paraQue: 'Chatbots e interfaces de IA',
    aprendizados: [105],
    status: 'atual',
  },
  {
    numero: 82,
    categoria: 12,
    nome: 'RAG',
    oQueE: 'Busca em documentos próprios para contextualizar a IA',
    paraQue: 'Chat sobre base de conhecimento (FAQ, docs, cursos)',
    aprendizados: [106],
    status: 'atual',
  },
  {
    numero: 83,
    categoria: 13,
    nome: 'Componentização',
    oQueE: 'Dividir a interface em partes independentes',
    paraQue: 'Reuso, manutenção e trabalho em equipe',
    aprendizados: [1, 5],
    status: 'atual',
  },
  {
    numero: 84,
    categoria: 13,
    nome: 'Estrutura de pastas por feature',
    oQueE: 'Organizar por funcionalidade, não só por tipo',
    paraQue: 'Projetos que crescem sem virar bagunça',
    aprendizados: [17, 89],
    status: 'atual',
  },
  {
    numero: 85,
    categoria: 13,
    nome: 'CRUD',
    oQueE: 'Create, Read, Update, Delete',
    paraQue: 'Padrão de quase todo sistema de cadastro',
    aprendizados: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
    status: 'atual',
  },
  {
    numero: 86,
    categoria: 13,
    nome: 'Camada de serviço (abstração de API)',
    oQueE: 'Uma função central para as requisições',
    paraQue: 'Trocar a API ou tratar erros num só lugar',
    aprendizados: [33],
    status: 'atual',
  },
  {
    numero: 87,
    categoria: 13,
    nome: 'Clean Code',
    oQueE: 'Nomes claros, funções pequenas, responsabilidade única',
    paraQue: 'Código fácil de ler e revisar',
    aprendizados: [53],
    status: 'atual',
  },
  {
    numero: 88,
    categoria: 13,
    nome: 'Composição polimórfica (asChild)',
    oQueE: 'Um componente que assume a forma de outro',
    paraQue: 'Componentes flexíveis de design system',
    aprendizados: [54],
    status: 'atual',
  },
  {
    numero: 89,
    categoria: 13,
    nome: 'Otimização consciente',
    oQueE: 'Medir antes de otimizar (memo, useMemo, useCallback)',
    paraQue: 'Evitar otimização prematura',
    aprendizados: [55],
    status: 'atual',
  },
  {
    numero: 90,
    categoria: 13,
    nome: 'Cache e deduplicação',
    oQueE: 'Não repetir a mesma requisição',
    paraQue: 'Performance e menos carga na API',
    aprendizados: [56],
    status: 'atual',
  },
  {
    numero: 91,
    categoria: 13,
    nome: 'SaaS multi-tenant',
    oQueE: 'Várias organizações isoladas numa aplicação',
    paraQue: 'Produtos B2B por assinatura',
    aprendizados: [103],
    status: 'atual',
  },
  {
    numero: 92,
    categoria: 13,
    nome: 'UI Clone (engenharia reversa de interface)',
    oQueE: 'Recriar interfaces reais para treinar',
    paraQue: 'Portfólio e domínio de layout',
    aprendizados: [68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
    status: 'atual',
    nota: 'método de estudo',
  },
  {
    numero: 93,
    categoria: 13,
    nome: 'Testes: Testing Library e Cypress',
    oQueE: 'Testes de componente e ponta a ponta (só citados)',
    paraQue: 'Garantir que a interface funciona; ⚠️ nenhum vídeo ensina',
    aprendizados: [1],
    status: 'atual',
    nota: 'lacuna',
  },
]
/* Fim da stack. */
