/*
 * Conteúdo da Trilha React: 12 módulos e 116 aprendizados em ordem de consumo.
 * A duração fica no texto original ("46 min", "2h34"); os minutos são
 * calculados pelo domínio, nunca guardados (estado derivado).
 */
import type { Aprendizado, Modulo } from '../dominio/tipos'

export const modulos: Modulo[] = [
  {
    numero: 1,
    titulo: 'Primeiros passos',
  },
  {
    numero: 2,
    titulo: 'Primeiro projeto e hooks a fundo',
  },
  {
    numero: 3,
    titulo: 'CRUD completo passo a passo',
    autor: 'Luiz Fernando Nunes',
  },
  {
    numero: 4,
    titulo: 'CRUD na prática: projetos e consumo de API',
  },
  {
    numero: 5,
    titulo: 'Estado global, rotas e dados do servidor',
  },
  {
    numero: 6,
    titulo: 'Formulários, qualidade de código e segurança',
  },
  {
    numero: 7,
    titulo: 'Interfaces modernas: Tailwind, shadcn e projetos',
  },
  {
    numero: 8,
    titulo: 'UI Clone: responsividade e animações',
  },
  {
    numero: 9,
    titulo: 'Next.js e renderização no servidor',
  },
  {
    numero: 10,
    titulo: 'Next.js avançado e React 18/19',
  },
  {
    numero: 11,
    titulo: 'Projetos reais, IA e ecossistema',
  },
  {
    numero: 12,
    titulo: 'Carreira e visão de mercado',
  },
]

export const aprendizados: Aprendizado[] = [
  {
    numero: 1,
    modulo: 1,
    titulo: 'Começando no React.js em 2022',
    duracao: '46 min',
    descricao:
      'Visão geral do React: por que usar Vite, criar o projeto, estrutura de pastas, componente como função, propriedades, estado, estilização, React Router e o mapa do que estudar depois.',
    youtubeId: 'pDbcC-xSat4',
  },
  {
    numero: 2,
    modulo: 1,
    titulo: 'Como começar em React em 2026?',
    duracao: '20 min',
    descricao:
      'Atualização do caminho de estudo para iniciantes: o que mudou no ecossistema e por onde começar hoje.',
    youtubeId: 'EOsigJta6cI',
  },
  {
    numero: 3,
    modulo: 1,
    titulo: 'Vai criar um projeto React? Veja esse vídeo antes',
    duracao: '13 min',
    descricao:
      'Apresentação da nova documentação oficial do React (react.dev) e das recomendações atuais para iniciar projetos.',
    youtubeId: '1ZDbOkW5ITs',
  },
  {
    numero: 4,
    modulo: 1,
    titulo: 'Configurando VSCode para Node.js, ReactJS e React Native',
    duracao: '22 min',
    descricao:
      'Configuração do editor: extensões, temas, ESLint e produtividade para desenvolvimento JavaScript.',
    youtubeId: 'c7P03kkrEG8',
    historico: true,
  },
  {
    numero: 5,
    modulo: 1,
    titulo: 'Simplificando o conceito de componentes e propriedades',
    duracao: '9 min',
    descricao:
      'Os dois pilares do React: o que é componente, o que é propriedade e como os dois se relacionam.',
    youtubeId: '00nfvN2UTZc',
  },
  {
    numero: 6,
    modulo: 1,
    titulo: 'Explorando useState no React',
    duracao: '5 min',
    descricao: 'Estado como variável observada: quando muda, a interface renderiza de novo.',
    youtubeId: 'mY9MLdifqe0',
  },
  {
    numero: 7,
    modulo: 1,
    titulo: 'React básico: o useEffect para chamada de API',
    duracao: '6 min',
    descricao:
      'Uso do useEffect para buscar dados de uma API e a diferença entre estado e efeito colateral.',
    youtubeId: 'L6raE_UfweY',
  },
  {
    numero: 8,
    modulo: 1,
    titulo: 'Estilização e reutilização de componentes personalizados',
    duracao: '9 min',
    descricao:
      'Como identificar padrões visuais repetidos e transformá-los em componentes reutilizáveis.',
    youtubeId: 'CiSgv2ZITdQ',
  },
  {
    numero: 9,
    modulo: 1,
    titulo: 'Explorando React Hooks: useState e seleção de arquivos de vídeo',
    duracao: '5 min',
    descricao: 'useState tipado com TypeScript aplicado à seleção de arquivo pelo input.',
    youtubeId: 'pyPiIsuIvnE',
  },
  {
    numero: 10,
    modulo: 1,
    titulo: 'Preview URL dinâmica com React e useMemo',
    duracao: '4 min',
    descricao: 'useMemo para evitar recálculos, gerando a pré-visualização do arquivo selecionado.',
    youtubeId: 'QMGyjAn1mwA',
  },
  {
    numero: 11,
    modulo: 2,
    titulo: 'React Portfolio Website From Scratch',
    duracao: '2h34',
    descricao:
      'Crash course com um site de portfólio responsivo: ES6, JSX, componentes, props, eventos, condicionais, React Router, hooks (useState, useEffect, useCallback, custom hooks) e estrutura de pastas.',
    youtubeId: '0h2b4ftbZcU',
    idioma: 'en',
    autor: 'Tech2 etc',
  },
  {
    numero: 12,
    modulo: 2,
    titulo: 'React Hooks na prática',
    duracao: '33 min',
    descricao:
      'Migração de componentes de classe para hooks: useState, useEffect, useMemo e useCallback na prática.',
    youtubeId: '6WB16wZS61c',
    historico: true,
  },
  {
    numero: 13,
    modulo: 2,
    titulo: 'Duas regras que você precisa cumprir com hooks',
    duracao: '18 min',
    descricao:
      'Como os hooks funcionam por dentro e por que não podem ficar em condicionais nem fora de componentes.',
    youtubeId: 'lRWf4WjfsVI',
  },
  {
    numero: 14,
    modulo: 2,
    titulo: 'O erro mais comum no React',
    duracao: '13 min',
    descricao:
      'Estados derivados: por que não criar estado a partir de informação que já existe, e como calcular direto.',
    youtubeId: 'kCpca2z2cls',
  },
  {
    numero: 15,
    modulo: 2,
    titulo: 'React useRef: controle o DOM com precisão',
    duracao: '11 min',
    descricao:
      'useRef para acessar elementos do DOM e guardar valores sem provocar nova renderização.',
    youtubeId: 'KcO9nCCNAqE',
  },
  {
    numero: 16,
    modulo: 2,
    titulo: 'Utilizando as refs no React de forma avançada',
    duracao: '34 min',
    descricao: 'forwardRef e useImperativeHandle: expor funções de um componente filho para o pai.',
    youtubeId: 'lA8o3kUl1TA',
  },
  {
    numero: 17,
    modulo: 2,
    titulo: 'Estrutura de pastas para ReactJS/React Native',
    duracao: '15 min',
    descricao:
      'Critérios para organizar pastas por tipo e por funcionalidade, e como escalar sem estrutura perfeita.',
    youtubeId: 'X2RKRKdqqwM',
  },
  {
    numero: 18,
    modulo: 2,
    titulo: 'Caminhos relativos no ReactJS com create-react-app',
    duracao: '11 min',
    descricao: 'Como evitar imports "../../../" configurando caminhos absolutos no projeto.',
    youtubeId: 'lAV1-19hHqw',
    historico: true,
  },
  {
    numero: 19,
    modulo: 2,
    titulo: 'Utilizando Styled Components (CSS-in-JS)',
    duracao: '12 min',
    descricao:
      'O conceito de CSS-in-JS e a criação de componentes estilizados no React e no React Native.',
    youtubeId: 'R3S8DEzEn6s',
    historico: true,
  },
  {
    numero: 20,
    modulo: 2,
    titulo: 'Theme Switcher com ReactJS e Context API',
    duracao: '17 min',
    descricao:
      'Troca de tema claro/escuro compartilhando estado entre componentes com a Context API.',
    youtubeId: 'oDgxUodLwGU',
    historico: true,
  },
  {
    numero: 21,
    modulo: 3,
    titulo: 'Parte 1: Apresentação do CRUD',
    duracao: '2 min',
    descricao: 'Demonstração da aplicação que será construída ao longo da série.',
    youtubeId: 'yzz78l4ydQk',
    autor: 'Luiz Fernando Nunes',
  },
  {
    numero: 22,
    modulo: 3,
    titulo: 'Parte 2: Iniciando um novo projeto React',
    duracao: '5 min',
    descricao: 'Criação do projeto com create-react-app e primeira execução.',
    youtubeId: 'G5EIh77grY0',
    autor: 'Luiz Fernando Nunes',
  },
  {
    numero: 23,
    modulo: 3,
    titulo: 'Parte 3: Criando seu próprio componente',
    duracao: '7 min',
    descricao: 'Remoção dos componentes de exemplo e criação de um componente do zero.',
    youtubeId: 'hcvvDN1i9ng',
    autor: 'Luiz Fernando Nunes',
  },
  {
    numero: 24,
    modulo: 3,
    titulo: 'Parte 4: Criando rotas para os componentes',
    duracao: '17 min',
    descricao: 'Troca de páginas com React Router.',
    youtubeId: '5e5NCnv2ZMU',
    autor: 'Luiz Fernando Nunes',
  },
  {
    numero: 25,
    modulo: 3,
    titulo: 'Parte 5: Abas de menu com React Bootstrap',
    duracao: '9 min',
    descricao: 'Navegação por abas usando o componente Tabs do React Bootstrap.',
    youtubeId: 'ULa42Q20dJk',
    autor: 'Luiz Fernando Nunes',
  },
  {
    numero: 26,
    modulo: 3,
    titulo: 'Parte 6: Criando tabela com React',
    duracao: '11 min',
    descricao: 'Listagem dos registros numa tabela do React Bootstrap.',
    youtubeId: '1Hz9Xakh12M',
    autor: 'Luiz Fernando Nunes',
  },
  {
    numero: 27,
    modulo: 3,
    titulo: 'Parte 7: Usando um State em React',
    duracao: '11 min',
    descricao: 'Manter a tabela atualizada a partir do estado do componente.',
    youtubeId: '4liMA_4lubI',
    autor: 'Luiz Fernando Nunes',
  },
  {
    numero: 28,
    modulo: 3,
    titulo: 'Parte 8: GET em uma API REST',
    duracao: '8 min',
    descricao: 'Leitura dos dados da API com a Fetch API (o R do CRUD).',
    youtubeId: 'yQhhmDGu3Kg',
    autor: 'Luiz Fernando Nunes',
  },
  {
    numero: 29,
    modulo: 3,
    titulo: 'Parte 9: DELETE em uma API REST',
    duracao: '8 min',
    descricao: 'Exclusão de registro pela API e atualização da lista.',
    youtubeId: 'AC5ryzYPXLQ',
    autor: 'Luiz Fernando Nunes',
  },
  {
    numero: 30,
    modulo: 3,
    titulo: 'Parte 10: POST em uma API REST',
    duracao: '19 min',
    descricao: 'Formulário de cadastro enviando novos registros para a API.',
    youtubeId: 'LyZcsspmJQE',
    autor: 'Luiz Fernando Nunes',
  },
  {
    numero: 31,
    modulo: 4,
    titulo: 'Parte 11: UPDATE em uma API REST',
    duracao: '15 min',
    descricao: 'Edição de registro existente: carregar no formulário e enviar a alteração.',
    youtubeId: 'NXufbjBIqa0',
    autor: 'Luiz Fernando Nunes',
  },
  {
    numero: 32,
    modulo: 4,
    titulo: 'Parte 12: Melhorando a interface com Modal e Bootstrap',
    duracao: '15 min',
    descricao: 'Formulário dentro de um modal para melhorar a experiência do CRUD.',
    youtubeId: 'lEvr6Qbb4Dg',
    autor: 'Luiz Fernando Nunes',
  },
  {
    numero: 33,
    modulo: 4,
    titulo: 'React CRUD Operations',
    duracao: '20 min',
    descricao:
      'Uma única função assíncrona de requisição reaproveitada para POST, PATCH e DELETE, com API simulada no JSON Server.',
    youtubeId: 'XYrNkTkx8Uc',
    idioma: 'en',
    autor: 'Dave Gray',
  },
  {
    numero: 34,
    modulo: 4,
    titulo: 'Sistema de Controle de Finanças com React.JS',
    duracao: '41 min',
    descricao:
      'Projeto de controle financeiro com totais de entradas, saídas e saldo, e os módulos de inclusão, exclusão e leitura.',
    youtubeId: 'pj4vA67olbU',
    autor: 'Will Dev',
  },
  {
    numero: 35,
    modulo: 4,
    titulo: 'CRUD Full Stack com Node, React & MySQL',
    duracao: '40 min',
    descricao: 'Cadastro de usuários de ponta a ponta: API em Node, front em React e banco MySQL.',
    youtubeId: 'voXTVTW73E8',
    autor: 'Will Dev',
  },
  {
    numero: 36,
    modulo: 4,
    titulo: 'Desafio 10: ReactJS CRUD, GoStack 11.0',
    duracao: '31 min',
    descricao: 'Resolução do desafio de CRUD do bootcamp da Rocketseat, com React e TypeScript.',
    youtubeId: 'atZax_qr6Vk',
    autor: 'Thiago Cedran',
  },
  {
    numero: 37,
    modulo: 4,
    titulo: 'Upload de arquivos: front-end com ReactJS',
    duracao: '1h18',
    descricao:
      'Interface completa de upload: arrastar e soltar, progresso e experiência do usuário.',
    youtubeId: 'G5UZmvkLWSQ',
    historico: true,
  },
  {
    numero: 38,
    modulo: 4,
    titulo: 'Deploy de aplicação NodeJS e ReactJS no Heroku',
    duracao: '25 min',
    descricao:
      'Colocar em produção o sistema de upload (back e front). O Heroku não tem mais plano gratuito.',
    youtubeId: '-j7vLmBMsEU',
    historico: true,
  },
  {
    numero: 39,
    modulo: 4,
    titulo: 'Consumindo APIs no React com SWR',
    duracao: '38 min',
    descricao:
      'Cache, revalidação e melhor experiência no consumo de API, em vez de useEffect + useState.',
    youtubeId: 'Pbs1VIwPoRA',
  },
  {
    numero: 40,
    modulo: 4,
    titulo: 'GraphQL no front-end com ReactJS e Apollo',
    duracao: '43 min',
    descricao: 'Consumo de API GraphQL com Apollo Client: queries e mutations.',
    youtubeId: 'mNiAwtKbcrk',
    historico: true,
  },
  {
    numero: 41,
    modulo: 5,
    titulo: 'Controlando autenticação em rotas',
    duracao: '13 min',
    descricao: 'Rotas privadas: bloquear o acesso de quem não está logado.',
    youtubeId: 'sYe4r8WXGQg',
    historico: true,
  },
  {
    numero: 42,
    modulo: 5,
    titulo: 'Desvendando o Redux na prática',
    duracao: '51 min',
    descricao: 'Store, actions e reducers: o fluxo do Redux explicado do zero.',
    youtubeId: 'u99tNt3TZf8',
    historico: true,
  },
  {
    numero: 43,
    modulo: 5,
    titulo: 'React Hooks + Redux',
    duracao: '16 min',
    descricao: 'useSelector e useDispatch no lugar do connect.',
    youtubeId: '7L7MhxjI4PE',
    historico: true,
  },
  {
    numero: 44,
    modulo: 5,
    titulo: 'Conectando o React Router DOM ao Redux',
    duracao: '9 min',
    descricao: 'Navegar depois de uma ação assíncrona (login com Redux Thunk e redirecionamento).',
    youtubeId: 'khaFn1pnDtw',
    historico: true,
  },
  {
    numero: 45,
    modulo: 5,
    titulo: 'TypeScript com ReactJS, Redux e Redux Saga',
    duracao: '51 min',
    descricao: 'Tipagem de componentes, store e efeitos colaterais com Saga.',
    youtubeId: 'OXxul6AvXNs',
    historico: true,
  },
  {
    numero: 46,
    modulo: 5,
    titulo: 'Tornando a Context API mais performática',
    duracao: '23 min',
    descricao: 'Limitações de performance do Context e como evitar renderizações desnecessárias.',
    youtubeId: 'JtO6UwQs8I0',
  },
  {
    numero: 47,
    modulo: 5,
    titulo: 'React Query: talvez você não precise de estados globais',
    duracao: '14 min',
    descricao: 'HTTP state: separar dados do servidor do estado da interface.',
    youtubeId: 'Q-206WRzOHQ',
  },
  {
    numero: 48,
    modulo: 5,
    titulo: 'Gerenciar estados de paginação com useQuery',
    duracao: '20 min',
    descricao: 'Paginação com React Query: chaves de cache e navegação entre páginas.',
    youtubeId: '7zb1-pR3Jxk',
  },
  {
    numero: 49,
    modulo: 5,
    titulo: 'Você não deveria usar estados do React pra tudo (URL State)',
    duracao: '10 min',
    descricao: 'Guardar filtros e paginação na URL para compartilhar e manter o estado.',
    youtubeId: 'YJmcyvrJf20',
  },
  {
    numero: 50,
    modulo: 5,
    titulo: 'Larguei o React Router pelo TanStack Router no meu SaaS',
    duracao: '17 min',
    descricao:
      'Comparação prática entre os dois roteadores: tipagem, rotas e experiência de desenvolvimento.',
    youtubeId: 'Z5H7s-6etbE',
  },
  {
    numero: 51,
    modulo: 6,
    titulo: 'A melhor forma de criar formulários (React Hook Form + Zod)',
    duracao: '8 min',
    descricao: 'Formulário performático com validação por schema.',
    youtubeId: 'DA39qCGt6RE',
  },
  {
    numero: 52,
    modulo: 6,
    titulo: 'Gerando slug usando React Hook Form',
    duracao: '15 min',
    descricao: 'Uso do watch para observar um campo e gerar outro automaticamente.',
    youtubeId: 'JQ5g0SOkBCM',
  },
  {
    numero: 53,
    modulo: 6,
    titulo: 'Refatorei um código React usando Clean Code',
    duracao: '31 min',
    descricao: 'Refatoração ao vivo de código real: nomes, responsabilidades e legibilidade.',
    youtubeId: 'qcIhUoBZaHg',
  },
  {
    numero: 54,
    modulo: 6,
    titulo: 'Esse pattern do React pode te salvar',
    duracao: '13 min',
    descricao:
      'Composição polimórfica (asChild, do Radix): um componente que assume o comportamento de outro.',
    youtubeId: 'zhgbanI0UV8',
  },
  {
    numero: 55,
    modulo: 6,
    titulo: 'Guia definitivo de performance (useMemo, useCallback, memo)',
    duracao: '54 min',
    descricao: 'Quando otimizar e quando otimização prematura atrapalha.',
    youtubeId: 'NmU2nNehNNY',
  },
  {
    numero: 56,
    modulo: 6,
    titulo: 'Dois conceitos para um app React/Next mais performático',
    duracao: '8 min',
    descricao: 'Cache e deduplicação de requisições.',
    youtubeId: '2RDuyw-NdDU',
  },
  {
    numero: 57,
    modulo: 6,
    titulo: 'O botão de Like perfeito com React Query',
    duracao: '16 min',
    descricao: 'Atualização otimista sem erros de hidratação.',
    youtubeId: 'pBs3738en9U',
  },
  {
    numero: 58,
    modulo: 6,
    titulo: 'Como lido com autorizações (permissões) nos meus apps',
    duracao: '7 min',
    descricao: 'Controle de permissões por papel (RBAC) na aplicação.',
    youtubeId: 'NG8qTapopj4',
  },
  {
    numero: 59,
    modulo: 6,
    titulo: 'Autenticação no React com Better Auth (+ back-end com Bun)',
    duracao: '24 min',
    descricao: 'Login completo com biblioteca moderna de autenticação e back-end próprio.',
    youtubeId: 'bZGpr0ECk0A',
  },
  {
    numero: 60,
    modulo: 6,
    titulo: 'Comunicação tipada entre front-end e back-end',
    duracao: '13 min',
    descricao: 'tRPC, Eden, ZSA e Orval: tipos compartilhados entre cliente e servidor.',
    youtubeId: 'iM_Rt3fJxQs',
  },
  {
    numero: 61,
    modulo: 7,
    titulo: 'Você não usa Tailwind por esse motivo? (mitos)',
    duracao: '16 min',
    descricao: 'Os argumentos contra o Tailwind analisados um a um.',
    youtubeId: 'EbFA4RQrc0w',
  },
  {
    numero: 62,
    modulo: 7,
    titulo: '3 dicas para escalar apps React com TailwindCSS',
    duracao: '15 min',
    descricao: 'Organizar classes e variantes em projetos grandes.',
    youtubeId: 'BhPyF0BQpF0',
  },
  {
    numero: 63,
    modulo: 7,
    titulo: 'Migrando uma aplicação React para Tailwind v4',
    duracao: '18 min',
    descricao: 'Migração real para a versão 4 e o que mudou.',
    youtubeId: '5m6xgXbkcl4',
  },
  {
    numero: 64,
    modulo: 7,
    titulo: 'Criando UI no React na velocidade da luz (shadcn/ui)',
    duracao: '15 min',
    descricao: 'Componentes acessíveis copiados para dentro do projeto e customizados.',
    youtubeId: 'er_QPBldsXE',
  },
  {
    numero: 65,
    modulo: 7,
    titulo: 'Gráficos interativos no React (shadcn + Recharts)',
    duracao: '3 min',
    descricao: 'Gráficos prontos integrados ao design system.',
    youtubeId: 'WEitNRycnpI',
  },
  {
    numero: 66,
    modulo: 7,
    titulo: 'O shadcn está abandonando o Radix UI?',
    duracao: '12 min',
    descricao: 'Mudança de base do shadcn e o impacto nos projetos.',
    youtubeId: 'YVOqvNkums0',
  },
  {
    numero: 67,
    modulo: 7,
    titulo: 'Do Figma para React com IA',
    duracao: '17 min',
    descricao: 'Geração automática de componentes a partir do design com IA.',
    youtubeId: 'bZso_6r9XR8',
  },
  {
    numero: 68,
    modulo: 7,
    titulo: 'Recriei a interface do Spotify usando Tailwind',
    duracao: '53 min',
    descricao: 'Projeto de interface completa com Tailwind.',
    youtubeId: 'YVI-q3idGiM',
  },
  {
    numero: 69,
    modulo: 7,
    titulo: 'Recriei o dashboard do iFood com React (app fullstack)',
    duracao: '13 min',
    descricao: 'Dashboard de restaurante de ponta a ponta.',
    youtubeId: 'GnxCqTl-0Ww',
  },
  {
    numero: 70,
    modulo: 7,
    titulo: 'App de whiteboard com React (UI do Figma Jam)',
    duracao: '45 min',
    descricao: 'Quadro interativo com arrastar, nós e conexões.',
    youtubeId: 'J3vbTM21uDs',
  },
  {
    numero: 71,
    modulo: 8,
    titulo: 'Twitter responsivo com ReactJS',
    duracao: '2h38',
    descricao: 'Layout responsivo completo com variáveis de cor e colunas.',
    youtubeId: 'K-8z_4xvT3o',
  },
  {
    numero: 72,
    modulo: 8,
    titulo: 'Recriando a interface do Discord com ReactJS',
    duracao: '2h23',
    descricao: 'Interface complexa construída do zero a partir de protótipo no Figma.',
    youtubeId: 'x4FdZd2-_uU',
  },
  {
    numero: 73,
    modulo: 8,
    titulo: 'Recriando interface do GitHub com ReactJS',
    duracao: '2h41',
    descricao: 'Navegação por rotas, responsividade e tema escuro.',
    youtubeId: 'iLEbGQXsg3k',
  },
  {
    numero: 74,
    modulo: 8,
    titulo: 'Recriando página do Dropbox com ReactJS',
    duracao: '1h10',
    descricao: 'Menu responsivo, múltiplos headers e a propriedade clip do CSS.',
    youtubeId: 'VqP1ECc_j4M',
  },
  {
    numero: 75,
    modulo: 8,
    titulo: 'LinkedIn e Shimmer Effect no ReactJS',
    duracao: '1h05',
    descricao: 'Esqueleto de carregamento (shimmer) para melhorar a UX.',
    youtubeId: '-ZV-_7vNRGw',
  },
  {
    numero: 76,
    modulo: 8,
    titulo: 'Página de produto do Mercado Livre com ReactJS',
    duracao: '1h02',
    descricao: 'Página de produto de e-commerce com atenção aos detalhes dos componentes.',
    youtubeId: 'APs_xQ2hUOE',
  },
  {
    numero: 77,
    modulo: 8,
    titulo: 'Homepage da Tesla com ReactJS',
    duracao: '1h32',
    descricao: 'Seções em tela cheia com rolagem e animação.',
    youtubeId: 'Mf4Se4ZGcG8',
  },
  {
    numero: 78,
    modulo: 8,
    titulo: 'Menu do Stripe com ReactJS',
    duracao: '2h23',
    descricao: 'Menu animado complexo com biblioteca de animação.',
    youtubeId: 'B7V0q0ZSz2o',
  },
  {
    numero: 79,
    modulo: 8,
    titulo: 'Homepage animada do Typeform com Framer Motion',
    duracao: '43 min',
    descricao: 'Animações declarativas com Framer Motion.',
    youtubeId: 'O2xM5H7Ooj4',
  },
  {
    numero: 80,
    modulo: 8,
    titulo: 'Como inicio meus apps com ReactJS?',
    duracao: '44 min',
    descricao: 'Setup profissional: Next.js, TypeScript, ESLint e Styled Components.',
    youtubeId: '1nVUfZg2dSA',
  },
  {
    numero: 81,
    modulo: 9,
    titulo: 'Server-side rendering no ReactJS com Next.js',
    duracao: '17 min',
    descricao: 'O conceito de SSR: renderizar no servidor e entregar a página pronta.',
    youtubeId: 'aQFPetOyzUE',
    historico: true,
  },
  {
    numero: 82,
    modulo: 9,
    titulo: 'Serverless com ReactJS e Next.js na Vercel',
    duracao: '34 min',
    descricao: 'API routes: back-end sem servidor dedicado dentro do Next.',
    youtubeId: 'Cz55Jmhfw84',
  },
  {
    numero: 83,
    modulo: 9,
    titulo: 'Tudo que você precisa saber do Next 13',
    duracao: '1h10',
    descricao: 'App Router, layouts, Server Components e a nova forma de buscar dados.',
    youtubeId: '0zl72thBKzo',
  },
  {
    numero: 84,
    modulo: 9,
    titulo: 'Meu novo site pessoal (Next.js 13)',
    duracao: '40 min',
    descricao: 'Projeto prático de site pessoal com o App Router.',
    youtubeId: 'PD9jFWLY8Is',
  },
  {
    numero: 85,
    modulo: 9,
    titulo: 'Server Components no React (tá lembrando o PHP?)',
    duracao: '25 min',
    descricao: 'Por que Server Components lembram renderização clássica no servidor, e o que muda.',
    youtubeId: '3KSxzW8x5pA',
  },
  {
    numero: 86,
    modulo: 9,
    titulo: 'Server Components do jeito certo',
    duracao: '26 min',
    descricao: 'A arquitetura oficial de Server Components na documentação do React.',
    youtubeId: 'L1osqF17iDM',
  },
  {
    numero: 87,
    modulo: 9,
    titulo: 'Server Components no React em 5 minutos',
    duracao: '5 min',
    descricao: 'Resumo rápido para fixar o conceito.',
    youtubeId: 'hdex1hj1dmk',
  },
  {
    numero: 88,
    modulo: 9,
    titulo: 'Eu resumi o Next.js 14 para você',
    duracao: '24 min',
    descricao: 'Server Components e Server Actions na versão 14.',
    youtubeId: '6JnkwfrAI-U',
  },
  {
    numero: 89,
    modulo: 9,
    titulo: 'Estrutura de pastas para Next.js (rotas privadas e públicas)',
    duracao: '21 min',
    descricao: 'Organização de rotas autenticadas e públicas no App Router.',
    youtubeId: 'nlc-l2nW_J0',
  },
  {
    numero: 90,
    modulo: 9,
    titulo: 'Quando usar React Query ou Server Components no Next.js',
    duracao: '15 min',
    descricao: 'Critérios para buscar dados no cliente ou no servidor.',
    youtubeId: 'kmZ0dQNQEWo',
  },
  {
    numero: 91,
    modulo: 10,
    titulo: 'A melhor forma de criar Server Actions no Next.js',
    duracao: '6 min',
    descricao: 'Server Actions com validação Zod, tratamento de erro e estado de carregamento.',
    youtubeId: 'xlH6zmdGz-E',
  },
  {
    numero: 92,
    modulo: 10,
    titulo: 'Vai criar um app full stack com Next.js? Essa é a melhor lib',
    duracao: '9 min',
    descricao: 'Biblioteca recomendada para ações seguras e tipadas no servidor.',
    youtubeId: 'QQODtUNXG9s',
  },
  {
    numero: 93,
    modulo: 10,
    titulo: 'Finalmente arrumaram o fetch (Next.js 15 RC)',
    duracao: '6 min',
    descricao: 'Mudanças no cache padrão do fetch no Next 15.',
    youtubeId: 'diJtzAVT8_Q',
  },
  {
    numero: 94,
    modulo: 10,
    titulo: 'Entenda o cache do Next.js de uma vez',
    duracao: '24 min',
    descricao: 'Cache tags e revalidação sob demanda.',
    youtubeId: 'YWek8a-4mmo',
  },
  {
    numero: 95,
    modulo: 10,
    titulo: 'A melhor forma de usar o cache do Next.js com JWT',
    duracao: '16 min',
    descricao: 'Cache em rotas autenticadas por token.',
    youtubeId: 'CW7CSsX39FE',
  },
  {
    numero: 96,
    modulo: 10,
    titulo: 'Deploy de apps React/Next.js na AWS (sem Vercel)',
    duracao: '46 min',
    descricao: 'Publicar SSR e SSG em infraestrutura própria.',
    youtubeId: 'keaS0Rr_eg8',
  },
  {
    numero: 97,
    modulo: 10,
    titulo: 'React 18: o que vai mudar no seu dia a dia?',
    duracao: '23 min',
    descricao: 'Renderização concorrente, batching automático e transições.',
    youtubeId: 'b04Tz5w4cXM',
  },
  {
    numero: 98,
    modulo: 10,
    titulo: 'React 19 RC é 10x mais simples para iniciantes',
    duracao: '14 min',
    descricao: 'Server Actions, refs como prop, o hook use e outras novidades.',
    youtubeId: 'Cg0LoRgAWsI',
  },
  {
    numero: 99,
    modulo: 10,
    titulo: 'Testando a nova função do React 19 (chega de useEffect)',
    duracao: '4 min',
    descricao: 'Teste ao vivo do novo hook que substitui parte dos usos do useEffect.',
    youtubeId: 'LVIxH7w_eUQ',
  },
  {
    numero: 100,
    modulo: 10,
    titulo: 'Formulários no React 19 com Server Actions',
    duracao: '14 min',
    descricao: 'Formulários com ações no servidor e validação.',
    youtubeId: 'WhVC332Ucb4',
  },
  {
    numero: 101,
    modulo: 11,
    titulo: 'React 19.2: testei as novidades',
    duracao: '14 min',
    descricao: 'Activity, useEffectEvent e outras novidades da versão 19.2.',
    youtubeId: 'QTrCIYbA8bE',
  },
  {
    numero: 102,
    modulo: 11,
    titulo: 'Estou criando um SaaS open-source com Next.js',
    duracao: '11 min',
    descricao: 'Planejamento e arquitetura de um SaaS real.',
    youtubeId: 'YjFE0pl11nw',
  },
  {
    numero: 103,
    modulo: 11,
    titulo: 'O código do meu novo app SaaS multi-tenant com Next.js',
    duracao: '15 min',
    descricao: 'Multi-tenant: várias organizações isoladas na mesma aplicação.',
    youtubeId: 'UVlFt05vND4',
  },
  {
    numero: 104,
    modulo: 11,
    titulo: 'Criei uma feature do zero em um projeto interno (Next.js + OpenAI)',
    duracao: '24 min',
    descricao: 'Funcionalidade com IA num projeto real, do problema à entrega.',
    youtubeId: 'Hg7etQH63M8',
  },
  {
    numero: 105,
    modulo: 11,
    titulo: 'Chatbot do zero com Next, AI SDK, OpenAI e shadcn/ui',
    duracao: '36 min',
    descricao: 'Chat com respostas em streaming e interface pronta.',
    youtubeId: 'CPRx_WVkJ8g',
  },
  {
    numero: 106,
    modulo: 11,
    titulo: 'Tutorial: como funciona o RAG na prática',
    duracao: '41 min',
    descricao: 'Busca em documentos próprios para dar contexto às respostas da IA.',
    youtubeId: 'cCydEfKRQMU',
  },
  {
    numero: 107,
    modulo: 11,
    titulo: 'Eu finalmente testei o framework Remix',
    duracao: '36 min',
    descricao: 'Primeiras impressões do Remix integrado ao React Router v7.',
    youtubeId: 'wdPCOXXtPt0',
  },
  {
    numero: 108,
    modulo: 11,
    titulo: 'Remix não terá novas versões',
    duracao: '5 min',
    descricao: 'O anúncio da React Conf e o novo rumo do framework.',
    youtubeId: 'v_iiNvxL7LU',
  },
  {
    numero: 109,
    modulo: 11,
    titulo: 'Meu primeiro app local-first com ElectricSQL e TanStack DB',
    duracao: '23 min',
    descricao: 'Dados sincronizados localmente, com funcionamento offline.',
    youtubeId: 'phO2BM1HLdM',
  },
  {
    numero: 110,
    modulo: 11,
    titulo: 'Finalizando app desktop com Tauri (Rust + React)',
    duracao: '22 min',
    descricao: 'React como interface de um aplicativo desktop.',
    youtubeId: 'lhkCa_v1buk',
  },
  {
    numero: 111,
    modulo: 12,
    titulo: 'Analisei as skills de React mais hypadas',
    duracao: '20 min',
    descricao: 'Avaliação crítica das habilidades mais comentadas do momento.',
    youtubeId: 'SwCcCf_iXGY',
  },
  {
    numero: 112,
    modulo: 12,
    titulo: 'Como se destacar como dev front-end na era da IA',
    duracao: '24 min',
    descricao: 'As 7 habilidades que diferenciam na primeira vaga.',
    youtubeId: 'XXW2KVs8cUQ',
  },
  {
    numero: 113,
    modulo: 12,
    titulo: 'Aplicações React do futuro?',
    duracao: '1h01',
    descricao: 'Visão geral sobre UI declarativa, design system e frameworks.',
    youtubeId: '6TEo2AxW-oQ',
  },
  {
    numero: 114,
    modulo: 12,
    titulo: 'O futuro do front-end e do React (Podcast FalaDev #08)',
    duracao: '37 min',
    descricao: 'Debate entre três devs sobre os rumos do React e do front-end.',
    youtubeId: 'GnA0k8gT6xw',
    historico: true,
  },
  {
    numero: 115,
    modulo: 12,
    titulo: 'Será que meu código é adequado? React ou Vue? (#PR 22)',
    duracao: '13 min',
    descricao: 'Perguntas e respostas da comunidade sobre escolhas técnicas.',
    youtubeId: 'U6RxX-cEHnM',
  },
  {
    numero: 116,
    modulo: 12,
    titulo: 'Iniciando no ReactJS (2017)',
    duracao: '10 min',
    descricao:
      'A primeira aula de React do canal, com componentes de classe: um fechamento para comparar como o React evoluiu.',
    youtubeId: '7A4UQGrFU9Q',
    historico: true,
  },
]
/* Fim do conteúdo da trilha. */
